# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
        image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm inatall -g npm@latest'
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test
          command: npm test



