version: 2 
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: sudo apt install vim
      - run: node -v
      - run: yarn install
      - run: pwd
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
