version: 2 
jobs:
  build:
    working_directory: ~
    docker:
        - image: circleci/node:10.13.0-browsers
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: sudo apt install vim
      - run: node -v
      - run: cat /etc/issue
      - run: uname -a
      - run: yarn install
      - run: pwd
      - run: ls node_modules
      - run: npm install
      - run: ls node_modules
      - run: cat package.json
      - run: npm run build
      - run: npm test 
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
